DROP TABLE  IF EXISTS  admin;
DROP TABLE  IF EXISTS  professor;
DROP TABLE  IF EXISTS  student;
DROP TABLE  IF EXISTS  log;
DROP TABLE  IF EXISTS  login;

create table login(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(32) not null,
	password varchar not null,
	created_by varchar(32) not null,
	updated_by varchar(32),
	created timestamp not null,
	updated timestamp,
	role integer not null,
	name varchar(64) not null
);

create table log(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_login integer not null,
	created_by varchar(32) not null,
	updated_by varchar(32) not null,
	created timestamp not null,
	updated timestamp not null,
	foreign key (id_login) references login(id)
);

create table admin(
	id integer not null,
	registration varchar(12) not null,
	primary key (id),
	foreign key (id) references login(id) 
	
);

create table professor(
	id integer not null,
	registration varchar(12) not null,
	primary key (id),
	foreign key (id) references login(id) 
);

create table student(
	id integer not null,
	registration varchar(12) not null,
	primary key (id),
	foreign key (id) references login(id) 
);

	